/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CARFPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian15 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  centralPath: "CENTRAL",
  projectsPath: "PROJECTS",
  enabledValidators: [
    "broken-links",
    "frontmatter",
    "orphans",
    "structure",
    "title",
    "stale",
    "empty-folders",
    "naming"
  ],
  autoUpdateTimestamp: true,
  autoValidateOnSave: true,
  autoSyncIndex: true,
  staleThresholdDays: 180
};
var CARFSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    var _a;
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "CARF Plugin Settings" });
    containerEl.createEl("h3", { text: "Paths" });
    new import_obsidian.Setting(containerEl).setName("Central path").setDesc("Path to CENTRAL folder").addText((text) => text.setPlaceholder("CENTRAL").setValue(this.plugin.settings.centralPath).onChange(async (value) => {
      this.plugin.settings.centralPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Projects path").setDesc("Path to PROJECTS folder").addText((text) => text.setPlaceholder("PROJECTS").setValue(this.plugin.settings.projectsPath).onChange(async (value) => {
      this.plugin.settings.projectsPath = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Automation" });
    new import_obsidian.Setting(containerEl).setName("Auto-update timestamp").setDesc("Automatically update 'updated' field when saving").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoUpdateTimestamp).onChange(async (value) => {
      this.plugin.settings.autoUpdateTimestamp = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-validate on save").setDesc("Run validation when saving a file").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoValidateOnSave).onChange(async (value) => {
      this.plugin.settings.autoValidateOnSave = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-sync README index").setDesc("Automatically update README index when files change").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoSyncIndex).onChange(async (value) => {
      this.plugin.settings.autoSyncIndex = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Stale threshold (days)").setDesc("Documents not updated after this many days are marked as stale").addText((text) => text.setPlaceholder("180").setValue(String(this.plugin.settings.staleThresholdDays)).onChange(async (value) => {
      const days = parseInt(value);
      if (!isNaN(days) && days > 0) {
        this.plugin.settings.staleThresholdDays = days;
        await this.plugin.saveSettings();
      }
    }));
    containerEl.createEl("h3", { text: "Validators" });
    const validators = ((_a = this.plugin.validationService) == null ? void 0 : _a.getValidators()) || [];
    for (const validator of validators) {
      new import_obsidian.Setting(containerEl).setName(validator.name).setDesc(validator.description).addToggle((toggle) => toggle.setValue(this.plugin.settings.enabledValidators.includes(validator.id)).onChange(async (value) => {
        var _a2;
        if (value) {
          if (!this.plugin.settings.enabledValidators.includes(validator.id)) {
            this.plugin.settings.enabledValidators.push(validator.id);
          }
        } else {
          this.plugin.settings.enabledValidators = this.plugin.settings.enabledValidators.filter((v) => v !== validator.id);
        }
        await this.plugin.saveSettings();
        (_a2 = this.plugin.validationService) == null ? void 0 : _a2.setValidatorEnabled(validator.id, value);
      }));
    }
  }
};

// src/services/MetadataService.ts
var import_obsidian2 = require("obsidian");

// src/models/types.ts
var DocType = /* @__PURE__ */ ((DocType5) => {
  DocType5["RF"] = "RF";
  DocType5["RNF"] = "RNF";
  DocType5["UC"] = "UC";
  DocType5["US"] = "US";
  DocType5["ARCH"] = "ARCH";
  DocType5["README"] = "README";
  DocType5["OTHER"] = "OTHER";
  return DocType5;
})(DocType || {});
var Status = /* @__PURE__ */ ((Status2) => {
  Status2["REVIEW"] = "review";
  Status2["APPROVED"] = "approved";
  Status2["REJECTED"] = "rejected";
  return Status2;
})(Status || {});
var VALID_MODULES = [
  "GEOAPI",
  "GEOWEB",
  "ADMIN",
  "KEYCLOAK",
  "WEBDOCS"
];
var REQUIRED_SECTIONS = {
  ["RF" /* RF */]: ["Crit\xE9rios de Aceita\xE7\xE3o", "Regras de Neg\xF3cio"],
  ["RNF" /* RNF */]: ["Crit\xE9rios de Aceita\xE7\xE3o", "M\xE9tricas"],
  ["UC" /* UC */]: ["Atores", "Pr\xE9-condi\xE7\xF5es", "Fluxo Principal", "Fluxos Alternativos", "P\xF3s-condi\xE7\xF5es"],
  ["US" /* US */]: ["Crit\xE9rios de Aceita\xE7\xE3o"],
  ["ARCH" /* ARCH */]: [],
  ["README" /* README */]: [],
  ["OTHER" /* OTHER */]: []
};
var TITLE_PATTERNS = {
  ["RF" /* RF */]: /^# RF-\d{3}: .+$/,
  ["RNF" /* RNF */]: /^# RNF-\d{3}: .+$/,
  ["UC" /* UC */]: /^# UC-\d{3}: .+$/,
  ["US" /* US */]: /^# US-\d{3}: .+$/,
  ["ARCH" /* ARCH */]: /^# .+$/,
  ["README" /* README */]: /^# .+$/,
  ["OTHER" /* OTHER */]: /^# .+$/
};
var NAMING_PATTERNS = {
  ["RF" /* RF */]: /^RF-\d{3}-.+\.md$/,
  ["RNF" /* RNF */]: /^RNF-\d{3}-.+\.md$/,
  ["UC" /* UC */]: /^\d{2}-UC-\d{3}-.+\.md$|^UC-\d{3}-.+\.md$/,
  ["US" /* US */]: /^US-\d{3}-.+\.md$/,
  ["ARCH" /* ARCH */]: /^\d{2}-.+\.md$/,
  ["README" /* README */]: /^README\.md$/,
  ["OTHER" /* OTHER */]: /.+\.md$/
};
var STALE_THRESHOLD_DAYS = 180;

// src/models/Document.ts
var Document = class {
  constructor(file, frontmatter, content, sections, links, title) {
    this.file = file;
    this.frontmatter = frontmatter;
    this.content = content;
    this.sections = sections;
    this.links = links;
    this.title = title;
  }
  /**
   * Get the document type from frontmatter or infer from filename
   */
  get type() {
    var _a;
    if ((_a = this.frontmatter) == null ? void 0 : _a.type) {
      return this.frontmatter.type;
    }
    return Document.inferTypeFromFilename(this.file.name);
  }
  /**
   * Get the document ID
   */
  get id() {
    var _a;
    return ((_a = this.frontmatter) == null ? void 0 : _a.id) || this.extractIdFromFilename();
  }
  /**
   * Get the document status
   */
  get status() {
    var _a;
    return ((_a = this.frontmatter) == null ? void 0 : _a.status) || "review" /* REVIEW */;
  }
  /**
   * Check if document has valid frontmatter
   */
  get hasValidFrontmatter() {
    return this.frontmatter !== null;
  }
  /**
   * Check if document is a CARF document (RF, RNF, UC, US)
   */
  get isCARFDocument() {
    const carfTypes = ["RF" /* RF */, "RNF" /* RNF */, "UC" /* UC */, "US" /* US */];
    return carfTypes.includes(this.type);
  }
  /**
   * Extract ID from filename (e.g., "RF-001-titulo.md" -> "RF-001")
   */
  extractIdFromFilename() {
    const match = this.file.name.match(/^(RF|RNF|UC|US)-\d{3}/);
    return match ? match[0] : null;
  }
  /**
   * Infer document type from filename
   */
  static inferTypeFromFilename(filename) {
    if (filename === "README.md")
      return "README" /* README */;
    if (filename.startsWith("RF-"))
      return "RF" /* RF */;
    if (filename.startsWith("RNF-"))
      return "RNF" /* RNF */;
    if (/^(\d{2}-)?UC-/.test(filename))
      return "UC" /* UC */;
    if (filename.startsWith("US-"))
      return "US" /* US */;
    if (/^\d{2}-.+\.md$/.test(filename))
      return "ARCH" /* ARCH */;
    return "OTHER" /* OTHER */;
  }
  /**
   * Check if file is in a CARF path
   */
  static isInCARFPath(path) {
    return path.startsWith("CENTRAL/") || path.startsWith("PROJECTS/");
  }
};

// src/services/MetadataService.ts
var MetadataService = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Parse a file into a Document object
   */
  async parseDocument(file) {
    const content = await this.app.vault.read(file);
    const frontmatter = this.parseFrontmatter(content);
    const bodyContent = this.getBodyContent(content);
    const sections = this.parseSections(bodyContent);
    const links = this.parseLinks(bodyContent);
    const title = this.parseTitle(bodyContent);
    return new Document(file, frontmatter, content, sections, links, title);
  }
  /**
   * Parse YAML frontmatter from content
   */
  parseFrontmatter(content) {
    const match = content.match(/^---\n([\s\S]*?)\n---/);
    if (!match)
      return null;
    try {
      const yaml = (0, import_obsidian2.parseYaml)(match[1]);
      if (!yaml)
        return null;
      return this.normalizeFrontmatter(yaml);
    } catch (e) {
      console.error("Failed to parse frontmatter:", e);
      return null;
    }
  }
  /**
   * Normalize raw YAML to CARFFrontmatter
   */
  normalizeFrontmatter(yaml) {
    if (!yaml.id || !yaml.type || !yaml.status) {
      return null;
    }
    const type = yaml.type.toUpperCase();
    if (!Object.values(DocType).includes(type)) {
      return null;
    }
    const status = yaml.status.toLowerCase();
    if (!Object.values(Status).includes(status)) {
      return null;
    }
    let modules = [];
    if (Array.isArray(yaml.modules)) {
      modules = yaml.modules.map((m) => m.toUpperCase()).filter((m) => VALID_MODULES.includes(m));
    }
    return {
      id: yaml.id,
      type,
      modules,
      epic: yaml.epic || void 0,
      status,
      created: yaml.created || this.formatDate(new Date()),
      updated: yaml.updated || this.formatDate(new Date())
    };
  }
  /**
   * Get body content without frontmatter
   */
  getBodyContent(content) {
    return content.replace(/^---\n[\s\S]*?\n---\n*/, "");
  }
  /**
   * Parse sections from body content
   */
  parseSections(content) {
    const sections = /* @__PURE__ */ new Map();
    const lines = content.split("\n");
    let currentSection = "";
    let currentContent = [];
    for (const line of lines) {
      const headerMatch = line.match(/^#{2,3}\s+(.+)$/);
      if (headerMatch) {
        if (currentSection) {
          sections.set(currentSection, currentContent.join("\n").trim());
        }
        currentSection = headerMatch[1].trim();
        currentContent = [];
      } else if (currentSection) {
        currentContent.push(line);
      }
    }
    if (currentSection) {
      sections.set(currentSection, currentContent.join("\n").trim());
    }
    return sections;
  }
  /**
   * Parse links from content
   */
  parseLinks(content) {
    const links = [];
    const lines = content.split("\n");
    for (let lineNum = 0; lineNum < lines.length; lineNum++) {
      const line = lines[lineNum];
      const wikiLinkRegex = /\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g;
      let match;
      while ((match = wikiLinkRegex.exec(line)) !== null) {
        links.push({
          target: match[1],
          line: lineNum + 1,
          column: match.index,
          type: "wiki",
          resolved: false
          // Will be resolved later
        });
      }
      const mdLinkRegex = /\[([^\]]+)\]\(([^)]+)\)/g;
      while ((match = mdLinkRegex.exec(line)) !== null) {
        const target = match[2];
        if (!target.startsWith("http://") && !target.startsWith("https://")) {
          links.push({
            target,
            line: lineNum + 1,
            column: match.index,
            type: "markdown",
            resolved: false
          });
        }
      }
    }
    return links;
  }
  /**
   * Parse title (H1) from content
   */
  parseTitle(content) {
    const match = content.match(/^#\s+(.+)$/m);
    return match ? match[1].trim() : null;
  }
  /**
   * Create default frontmatter for a new document
   */
  createDefaultFrontmatter(file) {
    const type = Document.inferTypeFromFilename(file.name);
    const id = this.extractIdFromFilename(file.name) || "";
    const now = this.formatDate(new Date());
    return {
      id,
      type,
      modules: [],
      epic: "",
      status: "review" /* REVIEW */,
      created: now,
      updated: now
    };
  }
  /**
   * Extract ID from filename
   */
  extractIdFromFilename(filename) {
    const match = filename.match(/^(RF|RNF|UC|US)-\d{3}/);
    return match ? match[0] : null;
  }
  /**
   * Format date as YYYY-MM-DD
   */
  formatDate(date) {
    return date.toISOString().split("T")[0];
  }
  /**
   * Add or update frontmatter in a file
   */
  async setFrontmatter(file, frontmatter) {
    const content = await this.app.vault.read(file);
    const bodyContent = this.getBodyContent(content);
    const yamlStr = (0, import_obsidian2.stringifyYaml)(frontmatter);
    const newContent = `---
${yamlStr}---

${bodyContent}`;
    await this.app.vault.modify(file, newContent);
  }
  /**
   * Update a single field in frontmatter
   */
  async updateFrontmatterField(file, field, value) {
    const content = await this.app.vault.read(file);
    const frontmatter = this.parseFrontmatter(content);
    if (!frontmatter) {
      throw new Error("File has no valid frontmatter");
    }
    frontmatter[field] = value;
    await this.setFrontmatter(file, frontmatter);
  }
  /**
   * Update the 'updated' timestamp
   */
  async updateTimestamp(file) {
    const content = await this.app.vault.read(file);
    const frontmatter = this.parseFrontmatter(content);
    if (frontmatter) {
      frontmatter.updated = this.formatDate(new Date());
      await this.setFrontmatter(file, frontmatter);
    }
  }
  /**
   * Set document status
   */
  async setStatus(file, status) {
    await this.updateFrontmatterField(file, "status", status);
    await this.updateFrontmatterField(file, "updated", this.formatDate(new Date()));
  }
  /**
   * Check if file has frontmatter
   */
  async hasFrontmatter(file) {
    const content = await this.app.vault.read(file);
    return this.parseFrontmatter(content) !== null;
  }
  /**
   * Initialize frontmatter for a file that doesn't have it
   */
  async initFrontmatter(file) {
    const frontmatter = this.createDefaultFrontmatter(file);
    await this.setFrontmatter(file, frontmatter);
    return frontmatter;
  }
};

// src/models/Issue.ts
var Issue = class {
  constructor(file, validator, severity, message, line = null, column = null, suggestion = null) {
    this.file = file;
    this.validator = validator;
    this.severity = severity;
    this.message = message;
    this.line = line;
    this.column = column;
    this.suggestion = suggestion;
  }
  /**
   * Create an error issue
   */
  static error(file, validator, message, line, suggestion) {
    return new Issue(file, validator, "error" /* ERROR */, message, line, null, suggestion);
  }
  /**
   * Create a warning issue
   */
  static warning(file, validator, message, line, suggestion) {
    return new Issue(file, validator, "warning" /* WARNING */, message, line, null, suggestion);
  }
  /**
   * Create an info issue
   */
  static info(file, validator, message, line, suggestion) {
    return new Issue(file, validator, "info" /* INFO */, message, line, null, suggestion);
  }
  /**
   * Get formatted location string
   */
  get location() {
    if (this.line !== null) {
      return `${this.file.name}:${this.line}`;
    }
    return this.file.name;
  }
  /**
   * Get severity icon
   */
  get icon() {
    switch (this.severity) {
      case "error" /* ERROR */:
        return "\u2717";
      case "warning" /* WARNING */:
        return "\u26A0";
      case "info" /* INFO */:
        return "\u2139";
    }
  }
  /**
   * Get severity class for styling
   */
  get severityClass() {
    return `carf-${this.severity}`;
  }
  /**
   * Compare issues for sorting (errors first, then warnings, then info)
   */
  static compare(a, b) {
    const severityOrder = {
      ["error" /* ERROR */]: 0,
      ["warning" /* WARNING */]: 1,
      ["info" /* INFO */]: 2
    };
    const severityDiff = severityOrder[a.severity] - severityOrder[b.severity];
    if (severityDiff !== 0)
      return severityDiff;
    const validatorDiff = a.validator.localeCompare(b.validator);
    if (validatorDiff !== 0)
      return validatorDiff;
    const fileDiff = a.file.path.localeCompare(b.file.path);
    if (fileDiff !== 0)
      return fileDiff;
    return (a.line || 0) - (b.line || 0);
  }
};
function calculateIssueSummary(issues) {
  return {
    total: issues.length,
    errors: issues.filter((i) => i.severity === "error" /* ERROR */).length,
    warnings: issues.filter((i) => i.severity === "warning" /* WARNING */).length,
    info: issues.filter((i) => i.severity === "info" /* INFO */).length
  };
}

// src/validators/BrokenLinksValidator.ts
var import_obsidian3 = require("obsidian");

// src/validators/Validator.ts
var LocalValidator = class {
  constructor() {
    this.isGlobal = false;
  }
};
var GlobalValidator = class {
  constructor() {
    this.isGlobal = true;
  }
};

// src/validators/BrokenLinksValidator.ts
var BrokenLinksValidator = class extends LocalValidator {
  constructor() {
    super(...arguments);
    this.id = "broken-links";
    this.name = "Broken Links";
    this.description = "Links que apontam para arquivos inexistentes";
  }
  async validateFile(document2, app) {
    const issues = [];
    for (const link of document2.links) {
      const resolved = this.resolveLink(link.target, document2.file, app);
      if (!resolved) {
        issues.push(Issue.error(
          document2.file,
          this.id,
          `Link "${link.target}" n\xE3o existe`,
          link.line,
          "Verifique se o caminho est\xE1 correto ou crie o arquivo"
        ));
      }
    }
    return issues;
  }
  /**
   * Resolve a link to a file
   */
  resolveLink(target, sourceFile, app) {
    var _a, _b;
    if (!target.includes("/") && !target.includes("\\")) {
      const files = app.vault.getMarkdownFiles();
      const targetWithExt = target.endsWith(".md") ? target : `${target}.md`;
      for (const file of files) {
        if (file.name === targetWithExt || file.basename === target) {
          return file;
        }
      }
      return null;
    }
    let resolvedPath;
    if (target.startsWith("./") || target.startsWith("../")) {
      const parentPath = ((_a = sourceFile.parent) == null ? void 0 : _a.path) || "";
      resolvedPath = this.resolvePath(parentPath, target);
    } else if (target.startsWith("/")) {
      resolvedPath = target.substring(1);
    } else {
      const parentPath = ((_b = sourceFile.parent) == null ? void 0 : _b.path) || "";
      resolvedPath = this.resolvePath(parentPath, "./" + target);
    }
    if (!resolvedPath.endsWith(".md")) {
      resolvedPath += ".md";
    }
    resolvedPath = (0, import_obsidian3.normalizePath)(resolvedPath);
    return app.vault.getAbstractFileByPath(resolvedPath);
  }
  /**
   * Resolve a relative path from a base path
   */
  resolvePath(basePath, relativePath) {
    const parts = basePath.split("/").filter((p) => p);
    const relParts = relativePath.split("/");
    for (const part of relParts) {
      if (part === "." || part === "") {
        continue;
      } else if (part === "..") {
        parts.pop();
      } else {
        parts.push(part);
      }
    }
    return parts.join("/");
  }
};

// src/validators/FrontmatterValidator.ts
var FrontmatterValidator = class extends LocalValidator {
  constructor() {
    super(...arguments);
    this.id = "frontmatter";
    this.name = "Frontmatter";
    this.description = "Campos obrigat\xF3rios no frontmatter";
  }
  async validateFile(document2, app) {
    const issues = [];
    if (!document2.isCARFDocument) {
      return issues;
    }
    if (!document2.frontmatter) {
      issues.push(Issue.error(
        document2.file,
        this.id,
        "Arquivo n\xE3o possui frontmatter YAML",
        1,
        "Execute 'CARF: Init Metadata' para criar o frontmatter"
      ));
      return issues;
    }
    const fm = document2.frontmatter;
    if (!fm.id) {
      issues.push(Issue.error(
        document2.file,
        this.id,
        "Campo 'id' obrigat\xF3rio no frontmatter",
        1,
        "Adicione o campo 'id' com o identificador do documento (ex: RF-001)"
      ));
    }
    if (!fm.type) {
      issues.push(Issue.error(
        document2.file,
        this.id,
        "Campo 'type' obrigat\xF3rio no frontmatter",
        1,
        "Adicione o campo 'type' com o tipo do documento (RF, RNF, UC, US)"
      ));
    }
    if (!fm.status) {
      issues.push(Issue.error(
        document2.file,
        this.id,
        "Campo 'status' obrigat\xF3rio no frontmatter",
        1,
        "Adicione o campo 'status' (review, approved, rejected)"
      ));
    }
    if (!fm.modules || fm.modules.length === 0) {
      issues.push(Issue.warning(
        document2.file,
        this.id,
        "Campo 'modules' est\xE1 vazio",
        1,
        `Adicione os m\xF3dulos relacionados: ${VALID_MODULES.join(", ")}`
      ));
    } else {
      for (const module2 of fm.modules) {
        if (!VALID_MODULES.includes(module2)) {
          issues.push(Issue.warning(
            document2.file,
            this.id,
            `M\xF3dulo '${module2}' n\xE3o \xE9 v\xE1lido`,
            1,
            `M\xF3dulos v\xE1lidos: ${VALID_MODULES.join(", ")}`
          ));
        }
      }
    }
    const expectedId = this.extractIdFromFilename(document2.file.name);
    if (expectedId && fm.id !== expectedId) {
      issues.push(Issue.warning(
        document2.file,
        this.id,
        `ID no frontmatter '${fm.id}' n\xE3o corresponde ao nome do arquivo '${expectedId}'`,
        1,
        `Corrija o ID para '${expectedId}'`
      ));
    }
    const expectedType = Document.inferTypeFromFilename(document2.file.name);
    if (expectedType !== "OTHER" /* OTHER */ && fm.type !== expectedType) {
      issues.push(Issue.warning(
        document2.file,
        this.id,
        `Tipo no frontmatter '${fm.type}' n\xE3o corresponde ao nome do arquivo`,
        1,
        `Corrija o tipo para '${expectedType}'`
      ));
    }
    return issues;
  }
  /**
   * Extract ID from filename
   */
  extractIdFromFilename(filename) {
    const match = filename.match(/^(RF|RNF|UC|US)-\d{3}/);
    return match ? match[0] : null;
  }
};

// src/validators/OrphansValidator.ts
var OrphansValidator = class extends GlobalValidator {
  constructor() {
    super(...arguments);
    this.id = "orphans";
    this.name = "Orphans";
    this.description = "Arquivos sem nenhum link apontando para eles";
  }
  async validateAll(documents, app) {
    const issues = [];
    const linkedFiles = /* @__PURE__ */ new Set();
    for (const doc of documents) {
      for (const link of doc.links) {
        const resolved = this.resolveLink(link.target, doc, documents);
        if (resolved) {
          linkedFiles.add(resolved.file.path);
        }
      }
    }
    for (const doc of documents) {
      if (!doc.isCARFDocument)
        continue;
      if (doc.type === "README" /* README */)
        continue;
      if (!linkedFiles.has(doc.file.path)) {
        issues.push(Issue.warning(
          doc.file,
          this.id,
          "Nenhum arquivo aponta para este documento",
          void 0,
          "Adicione um link para este documento em outro arquivo relacionado"
        ));
      }
    }
    return issues;
  }
  /**
   * Resolve a link target to a document
   */
  resolveLink(target, sourceDoc, documents) {
    var _a;
    const targetName = target.replace(/\.md$/, "");
    for (const doc of documents) {
      if (doc.file.path === target || doc.file.path === `${target}.md`) {
        return doc;
      }
      if (doc.file.basename === targetName) {
        return doc;
      }
      const sourcePath = ((_a = sourceDoc.file.parent) == null ? void 0 : _a.path) || "";
      const resolvedPath = this.resolvePath(sourcePath, target);
      if (doc.file.path === resolvedPath || doc.file.path === `${resolvedPath}.md`) {
        return doc;
      }
    }
    return null;
  }
  /**
   * Resolve a relative path from a base path
   */
  resolvePath(basePath, relativePath) {
    if (!relativePath.startsWith("./") && !relativePath.startsWith("../")) {
      return relativePath;
    }
    const parts = basePath.split("/").filter((p) => p);
    const relParts = relativePath.split("/");
    for (const part of relParts) {
      if (part === "." || part === "") {
        continue;
      } else if (part === "..") {
        parts.pop();
      } else {
        parts.push(part);
      }
    }
    return parts.join("/");
  }
};

// src/validators/StructureValidator.ts
var StructureValidator = class extends LocalValidator {
  constructor() {
    super(...arguments);
    this.id = "structure";
    this.name = "Structure";
    this.description = "Se\xE7\xF5es obrigat\xF3rias por tipo (## Crit\xE9rios, etc)";
  }
  async validateFile(document2, app) {
    const issues = [];
    if (!document2.isCARFDocument) {
      return issues;
    }
    const requiredSections = REQUIRED_SECTIONS[document2.type];
    if (!requiredSections || requiredSections.length === 0) {
      return issues;
    }
    const existingSections = Array.from(document2.sections.keys()).map((s) => this.normalizeSection(s));
    for (const required of requiredSections) {
      const normalizedRequired = this.normalizeSection(required);
      const found = existingSections.some((s) => s.includes(normalizedRequired) || normalizedRequired.includes(s));
      if (!found) {
        issues.push(Issue.warning(
          document2.file,
          this.id,
          `Se\xE7\xE3o obrigat\xF3ria '${required}' n\xE3o encontrada`,
          void 0,
          `Adicione a se\xE7\xE3o '## ${required}' ao documento`
        ));
      }
    }
    return issues;
  }
  /**
   * Normalize section name for comparison
   */
  normalizeSection(section) {
    return section.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]/g, "");
  }
};

// src/validators/TitleValidator.ts
var TitleValidator = class extends LocalValidator {
  constructor() {
    super(...arguments);
    this.id = "title";
    this.name = "Title";
    this.description = "H1 deve seguir padr\xE3o (# RF-001: T\xEDtulo)";
  }
  async validateFile(document2, app) {
    var _a;
    const issues = [];
    if (!document2.isCARFDocument) {
      return issues;
    }
    if (!document2.title) {
      issues.push(Issue.error(
        document2.file,
        this.id,
        "Documento n\xE3o possui t\xEDtulo (H1)",
        void 0,
        "Adicione um t\xEDtulo no formato '# ID: T\xEDtulo'"
      ));
      return issues;
    }
    const pattern = TITLE_PATTERNS[document2.type];
    if (pattern && !pattern.test(`# ${document2.title}`)) {
      const expectedFormat = this.getExpectedFormat(document2.type);
      issues.push(Issue.error(
        document2.file,
        this.id,
        `T\xEDtulo n\xE3o segue o padr\xE3o esperado`,
        this.findTitleLine(document2.content),
        `Formato esperado: ${expectedFormat}`
      ));
    }
    if ((_a = document2.frontmatter) == null ? void 0 : _a.id) {
      const titleId = this.extractIdFromTitle(document2.title);
      if (titleId && titleId !== document2.frontmatter.id) {
        issues.push(Issue.warning(
          document2.file,
          this.id,
          `ID no t\xEDtulo '${titleId}' n\xE3o corresponde ao frontmatter '${document2.frontmatter.id}'`,
          this.findTitleLine(document2.content),
          `Corrija o ID no t\xEDtulo para '${document2.frontmatter.id}'`
        ));
      }
    }
    return issues;
  }
  /**
   * Get expected title format for a document type
   */
  getExpectedFormat(type) {
    switch (type) {
      case "RF" /* RF */:
        return "# RF-XXX: T\xEDtulo do Requisito";
      case "RNF" /* RNF */:
        return "# RNF-XXX: T\xEDtulo do Requisito";
      case "UC" /* UC */:
        return "# UC-XXX: T\xEDtulo do Caso de Uso";
      case "US" /* US */:
        return "# US-XXX: T\xEDtulo da User Story";
      default:
        return "# T\xEDtulo";
    }
  }
  /**
   * Extract ID from title
   */
  extractIdFromTitle(title) {
    const match = title.match(/^(RF|RNF|UC|US)-\d{3}/);
    return match ? match[0] : null;
  }
  /**
   * Find the line number of the title
   */
  findTitleLine(content) {
    const lines = content.split("\n");
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].startsWith("# ")) {
        return i + 1;
      }
    }
    return 1;
  }
};

// src/validators/StaleValidator.ts
var StaleValidator = class extends LocalValidator {
  constructor() {
    super(...arguments);
    this.id = "stale";
    this.name = "Stale";
    this.description = "Arquivos n\xE3o atualizados h\xE1 >6 meses";
  }
  async validateFile(document2, app) {
    var _a;
    const issues = [];
    if (!document2.isCARFDocument) {
      return issues;
    }
    if (!((_a = document2.frontmatter) == null ? void 0 : _a.updated)) {
      return issues;
    }
    const updatedDate = new Date(document2.frontmatter.updated);
    const now = new Date();
    const daysSinceUpdate = Math.floor(
      (now.getTime() - updatedDate.getTime()) / (1e3 * 60 * 60 * 24)
    );
    if (daysSinceUpdate > STALE_THRESHOLD_DAYS) {
      const months = Math.floor(daysSinceUpdate / 30);
      issues.push(Issue.info(
        document2.file,
        this.id,
        `Documento n\xE3o atualizado h\xE1 ${months} meses`,
        void 0,
        "Revise o documento e atualize se necess\xE1rio"
      ));
    }
    return issues;
  }
};

// src/validators/EmptyFoldersValidator.ts
var import_obsidian4 = require("obsidian");
var EmptyFoldersValidator = class extends GlobalValidator {
  constructor() {
    super(...arguments);
    this.id = "empty-folders";
    this.name = "Empty Folders";
    this.description = "Pastas com README mas sem conte\xFAdo";
  }
  async validateAll(documents, app) {
    var _a;
    const issues = [];
    const folderDocs = /* @__PURE__ */ new Map();
    for (const doc of documents) {
      const folderPath = ((_a = doc.file.parent) == null ? void 0 : _a.path) || "";
      if (!folderDocs.has(folderPath)) {
        folderDocs.set(folderPath, []);
      }
      folderDocs.get(folderPath).push(doc);
    }
    for (const [folderPath, docs] of folderDocs) {
      if (!folderPath)
        continue;
      if (!folderPath.startsWith("CENTRAL/") && !folderPath.startsWith("PROJECTS/")) {
        continue;
      }
      const readme = docs.find((d) => d.file.name === "README.md");
      if (!readme)
        continue;
      const contentFiles = docs.filter((d) => d.file.name !== "README.md");
      const folder = app.vault.getAbstractFileByPath(folderPath);
      const hasSubfolders = folder instanceof import_obsidian4.TFolder && folder.children.some((c) => c instanceof import_obsidian4.TFolder);
      if (contentFiles.length === 0 && !hasSubfolders) {
        issues.push(Issue.warning(
          readme.file,
          this.id,
          "Pasta possui README mas n\xE3o tem conte\xFAdo",
          void 0,
          "Adicione arquivos de conte\xFAdo ou remova a pasta se n\xE3o for necess\xE1ria"
        ));
      }
    }
    return issues;
  }
};

// src/validators/NamingValidator.ts
var NamingValidator = class extends LocalValidator {
  constructor() {
    super(...arguments);
    this.id = "naming";
    this.name = "Naming";
    this.description = "Arquivos sem prefixo num\xE9rico correto";
  }
  async validateFile(document2, app) {
    const issues = [];
    if (document2.file.name === "README.md") {
      return issues;
    }
    const path = document2.file.path;
    if (!this.requiresNamingConvention(path)) {
      return issues;
    }
    const expectedType = this.getExpectedTypeFromPath(path);
    if (!expectedType) {
      return issues;
    }
    const pattern = NAMING_PATTERNS[expectedType];
    if (pattern && !pattern.test(document2.file.name)) {
      const expectedFormat = this.getExpectedFormat(expectedType);
      issues.push(Issue.error(
        document2.file,
        this.id,
        `Nome do arquivo n\xE3o segue o padr\xE3o esperado`,
        void 0,
        `Formato esperado: ${expectedFormat}`
      ));
    }
    return issues;
  }
  /**
   * Check if path requires naming convention
   */
  requiresNamingConvention(path) {
    const conventionPaths = [
      "CENTRAL/REQUIREMENTS/FUNCTIONAL",
      "CENTRAL/REQUIREMENTS/NON-FUNCTIONAL",
      "CENTRAL/REQUIREMENTS/USE-CASES",
      "CENTRAL/REQUIREMENTS/USER-STORIES",
      "PROJECTS/"
    ];
    return conventionPaths.some((p) => path.includes(p));
  }
  /**
   * Get expected document type from path
   */
  getExpectedTypeFromPath(path) {
    if (path.includes("/FUNCTIONAL/"))
      return "RF" /* RF */;
    if (path.includes("/NON-FUNCTIONAL/"))
      return "RNF" /* RNF */;
    if (path.includes("/USE-CASES/"))
      return "UC" /* UC */;
    if (path.includes("/USER-STORIES/"))
      return "US" /* US */;
    if (path.includes("/ARCHITECTURE/") || path.includes("/DOCS/"))
      return "ARCH" /* ARCH */;
    return null;
  }
  /**
   * Get expected file name format
   */
  getExpectedFormat(type) {
    switch (type) {
      case "RF" /* RF */:
        return "RF-XXX-nome-do-requisito.md";
      case "RNF" /* RNF */:
        return "RNF-XXX-nome-do-requisito.md";
      case "UC" /* UC */:
        return "XX-UC-XXX-nome-do-caso.md ou UC-XXX-nome-do-caso.md";
      case "US" /* US */:
        return "US-XXX-nome-da-historia.md";
      case "ARCH" /* ARCH */:
        return "XX-nome-do-documento.md";
      default:
        return "nome-do-arquivo.md";
    }
  }
};

// src/services/ValidationService.ts
var ValidationService = class {
  constructor(app, metadataService) {
    this.lastResult = null;
    this.app = app;
    this.metadataService = metadataService;
    this.validators = /* @__PURE__ */ new Map();
    this.enabledValidators = /* @__PURE__ */ new Set();
    this.registerValidators();
  }
  /**
   * Register all available validators
   */
  registerValidators() {
    const validators = [
      new BrokenLinksValidator(),
      new FrontmatterValidator(),
      new OrphansValidator(),
      new StructureValidator(),
      new TitleValidator(),
      new StaleValidator(),
      new EmptyFoldersValidator(),
      new NamingValidator()
    ];
    for (const validator of validators) {
      this.validators.set(validator.id, validator);
      this.enabledValidators.add(validator.id);
    }
  }
  /**
   * Enable or disable a validator
   */
  setValidatorEnabled(id, enabled) {
    if (!this.validators.has(id))
      return;
    if (enabled) {
      this.enabledValidators.add(id);
    } else {
      this.enabledValidators.delete(id);
    }
  }
  /**
   * Get all registered validators
   */
  getValidators() {
    return Array.from(this.validators.values());
  }
  /**
   * Get enabled validators
   */
  getEnabledValidators() {
    return Array.from(this.validators.values()).filter((v) => this.enabledValidators.has(v.id));
  }
  /**
   * Validate a single file
   */
  async validateFile(file) {
    if (!file.name.endsWith(".md"))
      return [];
    if (!Document.isInCARFPath(file.path))
      return [];
    const document2 = await this.metadataService.parseDocument(file);
    const issues = [];
    for (const validator of this.getEnabledValidators()) {
      if (!validator.isGlobal && validator.validateFile) {
        const validatorIssues = await validator.validateFile(document2, this.app);
        issues.push(...validatorIssues);
      }
    }
    return issues;
  }
  /**
   * Validate all files in the vault
   */
  async validateAll() {
    const files = this.getCARFFiles();
    const documents = [];
    const issues = [];
    for (const file of files) {
      const document2 = await this.metadataService.parseDocument(file);
      documents.push(document2);
    }
    for (const document2 of documents) {
      for (const validator of this.getEnabledValidators()) {
        if (!validator.isGlobal && validator.validateFile) {
          const validatorIssues = await validator.validateFile(document2, this.app);
          issues.push(...validatorIssues);
        }
      }
    }
    for (const validator of this.getEnabledValidators()) {
      if (validator.isGlobal && validator.validateAll) {
        const validatorIssues = await validator.validateAll(documents, this.app);
        issues.push(...validatorIssues);
      }
    }
    issues.sort(Issue.compare);
    const result = {
      issues,
      summary: calculateIssueSummary(issues),
      documents,
      timestamp: new Date()
    };
    this.lastResult = result;
    return result;
  }
  /**
   * Get the last validation result
   */
  getLastResult() {
    return this.lastResult;
  }
  /**
   * Get all markdown files in vault (except .obsidian, .git, node_modules)
   */
  getCARFFiles() {
    const ignorePaths = [".obsidian", ".git", "node_modules", ".plugins", ".scripts"];
    return this.app.vault.getMarkdownFiles().filter((file) => {
      return !ignorePaths.some((p) => file.path.startsWith(p + "/") || file.path.startsWith(p));
    });
  }
  /**
   * Get documents by status
   */
  getDocumentsByStatus(documents) {
    return {
      review: documents.filter((d) => d.status === "review"),
      approved: documents.filter((d) => d.status === "approved"),
      rejected: documents.filter((d) => d.status === "rejected")
    };
  }
  /**
   * Get issues grouped by validator
   */
  getIssuesByValidator(issues) {
    const grouped = /* @__PURE__ */ new Map();
    for (const issue of issues) {
      const existing = grouped.get(issue.validator) || [];
      existing.push(issue);
      grouped.set(issue.validator, existing);
    }
    return grouped;
  }
};

// src/services/IndexService.ts
var import_obsidian5 = require("obsidian");
var IndexService = class {
  constructor(app, metadataService) {
    this.pendingSyncs = /* @__PURE__ */ new Set();
    this.syncTimeout = null;
    this.app = app;
    this.metadataService = metadataService;
  }
  /**
   * Schedule a sync for a folder (debounced)
   */
  scheduleSync(folder) {
    this.pendingSyncs.add(folder.path);
    if (this.syncTimeout) {
      clearTimeout(this.syncTimeout);
    }
    this.syncTimeout = setTimeout(() => {
      this.processPendingSyncs();
    }, 2e3);
  }
  /**
   * Process all pending sync requests
   */
  async processPendingSyncs() {
    const folders = Array.from(this.pendingSyncs);
    this.pendingSyncs.clear();
    for (const folderPath of folders) {
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (folder instanceof import_obsidian5.TFolder) {
        await this.syncFolderIndex(folder);
      }
    }
  }
  /**
   * Sync the README index for a folder
   */
  async syncFolderIndex(folder) {
    const readmePath = `${folder.path}/README.md`;
    let readme = this.app.vault.getAbstractFileByPath(readmePath);
    const files = folder.children.filter((f) => f instanceof import_obsidian5.TFile && f.name.endsWith(".md") && f.name !== "README.md").sort((a, b) => a.name.localeCompare(b.name));
    const subfolders = folder.children.filter((f) => f instanceof import_obsidian5.TFolder).sort((a, b) => a.name.localeCompare(b.name));
    const indexContent = await this.generateIndexContent(folder, files, subfolders);
    if (readme) {
      const currentContent = await this.app.vault.read(readme);
      const newContent = this.updateIndexSection(currentContent, indexContent);
      if (newContent !== currentContent) {
        await this.app.vault.modify(readme, newContent);
      }
    }
  }
  /**
   * Generate index content for files and subfolders
   */
  async generateIndexContent(folder, files, subfolders) {
    const lines = [];
    if (subfolders.length > 0) {
      lines.push("## Subpastas");
      lines.push("");
      for (const subfolder of subfolders) {
        const folderName = subfolder.name;
        lines.push(`- [[${subfolder.path}/README|${folderName}]]`);
      }
      lines.push("");
    }
    if (files.length > 0) {
      lines.push("## Documentos");
      lines.push("");
      const docsByStatus = /* @__PURE__ */ new Map();
      for (const file of files) {
        const doc = await this.metadataService.parseDocument(file);
        const status = doc.status || "review" /* REVIEW */;
        if (!docsByStatus.has(status)) {
          docsByStatus.set(status, []);
        }
        docsByStatus.get(status).push(file);
      }
      const statusOrder = ["review" /* REVIEW */, "approved" /* APPROVED */, "rejected" /* REJECTED */];
      const statusLabels = {
        ["review" /* REVIEW */]: "Em Revis\xE3o",
        ["approved" /* APPROVED */]: "Aprovados",
        ["rejected" /* REJECTED */]: "Rejeitados"
      };
      for (const status of statusOrder) {
        const statusFiles = docsByStatus.get(status);
        if (statusFiles && statusFiles.length > 0) {
          lines.push(`### ${statusLabels[status]}`);
          lines.push("");
          for (const file of statusFiles) {
            const doc = await this.metadataService.parseDocument(file);
            const title = doc.title || file.basename;
            const icon = this.getStatusIcon(status);
            lines.push(`- ${icon} [[${file.path}|${title}]]`);
          }
          lines.push("");
        }
      }
    }
    return lines.join("\n");
  }
  /**
   * Get status icon
   */
  getStatusIcon(status) {
    switch (status) {
      case "approved" /* APPROVED */:
        return "\u2713";
      case "rejected" /* REJECTED */:
        return "\u2717";
      case "review" /* REVIEW */:
      default:
        return "\u25CB";
    }
  }
  /**
   * Update the index section in README content
   */
  updateIndexSection(content, indexContent) {
    const startMarker = "<!-- CARF-INDEX-START -->";
    const endMarker = "<!-- CARF-INDEX-END -->";
    const startIdx = content.indexOf(startMarker);
    const endIdx = content.indexOf(endMarker);
    if (startIdx !== -1 && endIdx !== -1) {
      const before = content.substring(0, startIdx);
      const after = content.substring(endIdx + endMarker.length);
      return `${before}${startMarker}
${indexContent}
${endMarker}${after}`;
    }
    const separator = content.endsWith("\n") ? "" : "\n";
    return `${content}${separator}
${startMarker}
${indexContent}
${endMarker}
`;
  }
  /**
   * Check if a file change should trigger index sync
   */
  shouldSyncIndex(file) {
    if (!file.name.endsWith(".md"))
      return false;
    if (!Document.isInCARFPath(file.path))
      return false;
    const folder = file.parent;
    if (!folder)
      return false;
    const readmePath = `${folder.path}/README.md`;
    return this.app.vault.getAbstractFileByPath(readmePath) !== null;
  }
};

// src/services/MigrationService.ts
var import_obsidian6 = require("obsidian");
var MigrationService = class {
  constructor(app, metadataService) {
    this.app = app;
    this.metadataService = metadataService;
  }
  /**
   * Migrate a single file from footer to frontmatter
   */
  async migrateFile(file) {
    const content = await this.app.vault.read(file);
    if (content.startsWith("---\n")) {
      return {
        file,
        success: false,
        message: "Arquivo j\xE1 possui frontmatter"
      };
    }
    const footerData = this.extractFooterMetadata(content);
    if (!footerData) {
      return {
        file,
        success: false,
        message: "Nenhum footer de metadados encontrado"
      };
    }
    const frontmatter = this.createFrontmatterFromFooter(file, footerData);
    const contentWithoutFooter = this.removeFooter(content);
    const newContent = this.addFrontmatter(contentWithoutFooter, frontmatter);
    await this.app.vault.modify(file, newContent);
    return {
      file,
      success: true,
      message: "Migra\xE7\xE3o conclu\xEDda com sucesso",
      oldFooter: footerData.raw,
      newFrontmatter: frontmatter
    };
  }
  /**
   * Migrate all files in the vault
   */
  async migrateAll() {
    const results = [];
    const files = this.getCARFFiles();
    let migrated = 0;
    let skipped = 0;
    let failed = 0;
    for (const file of files) {
      const result = await this.migrateFile(file);
      results.push(result);
      if (result.success) {
        migrated++;
      } else if (result.message.includes("j\xE1 possui")) {
        skipped++;
      } else {
        failed++;
      }
    }
    new import_obsidian6.Notice(
      `Migra\xE7\xE3o conclu\xEDda:
\u2713 ${migrated} migrados
\u25CB ${skipped} j\xE1 tinham frontmatter
\u2717 ${failed} falharam`
    );
    return results;
  }
  /**
   * Extract metadata from old footer format
   */
  extractFooterMetadata(content) {
    const footerPatterns = [
      // Pattern 1: Horizontal rules around metadata
      /\n---\n([\s\S]*?\*\*Status:\*\*[\s\S]*?)\n---\s*$/,
      // Pattern 2: Just metadata at end of file
      /\n(\*\*Status:\*\*[^\n]*(?:\n\*\*[^*]+:\*\*[^\n]*)*)\s*$/,
      // Pattern 3: Metadata section with header
      /\n##\s*Meta(?:dados?|data)?\s*\n([\s\S]*?\*\*Status:\*\*[\s\S]*?)$/i
    ];
    let footerMatch = null;
    for (const pattern of footerPatterns) {
      footerMatch = content.match(pattern);
      if (footerMatch)
        break;
    }
    if (!footerMatch)
      return null;
    const footerContent = footerMatch[1];
    const data = { raw: footerMatch[0] };
    const statusMatch = footerContent.match(/\*\*Status:\*\*\s*(\w+)/i);
    if (statusMatch) {
      data.status = this.normalizeStatus(statusMatch[1]);
    }
    const modulesMatch = footerContent.match(/\*\*M[óo]dulos?:\*\*\s*([^\n]+)/i);
    if (modulesMatch) {
      data.modules = this.parseModules(modulesMatch[1]);
    }
    const epicMatch = footerContent.match(/\*\*Epic:\*\*\s*([^\n]+)/i);
    if (epicMatch) {
      data.epic = epicMatch[1].trim();
    }
    const createdMatch = footerContent.match(/\*\*Cria[çc][ãa]o:\*\*\s*([^\n]+)/i);
    if (createdMatch) {
      data.created = this.parseDate(createdMatch[1]);
    }
    const updatedMatch = footerContent.match(/\*\*Atualiza[çc][ãa]o:\*\*\s*([^\n]+)/i);
    if (updatedMatch) {
      data.updated = this.parseDate(updatedMatch[1]);
    }
    return data;
  }
  /**
   * Normalize status value
   */
  normalizeStatus(status) {
    const normalized = status.toLowerCase().trim();
    switch (normalized) {
      case "approved":
      case "aprovado":
        return "approved" /* APPROVED */;
      case "rejected":
      case "rejeitado":
        return "rejected" /* REJECTED */;
      case "review":
      case "revis\xE3o":
      case "revisao":
      case "em revis\xE3o":
      case "em revisao":
      default:
        return "review" /* REVIEW */;
    }
  }
  /**
   * Parse modules from string
   */
  parseModules(modulesStr) {
    return modulesStr.split(/[,;]/).map((m) => m.trim().toUpperCase()).filter((m) => VALID_MODULES.includes(m));
  }
  /**
   * Parse date from string
   */
  parseDate(dateStr) {
    const cleaned = dateStr.trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(cleaned)) {
      return cleaned;
    }
    const brMatch = cleaned.match(/(\d{2})\/(\d{2})\/(\d{4})/);
    if (brMatch) {
      return `${brMatch[3]}-${brMatch[2]}-${brMatch[1]}`;
    }
    try {
      const date = new Date(cleaned);
      if (!isNaN(date.getTime())) {
        return date.toISOString().split("T")[0];
      }
    } catch (e) {
    }
    return new Date().toISOString().split("T")[0];
  }
  /**
   * Create frontmatter from extracted footer data
   */
  createFrontmatterFromFooter(file, footerData) {
    const type = Document.inferTypeFromFilename(file.name);
    const id = this.extractIdFromFilename(file.name) || "";
    const now = this.metadataService.formatDate(new Date());
    return {
      id,
      type,
      modules: footerData.modules || [],
      epic: footerData.epic || "",
      status: footerData.status || "review" /* REVIEW */,
      created: footerData.created || now,
      updated: footerData.updated || now
    };
  }
  /**
   * Extract ID from filename
   */
  extractIdFromFilename(filename) {
    const match = filename.match(/^(RF|RNF|UC|US)-\d{3}/);
    return match ? match[0] : null;
  }
  /**
   * Remove footer from content
   */
  removeFooter(content) {
    const footerPatterns = [
      /\n---\n[\s\S]*?\*\*Status:\*\*[\s\S]*?\n---\s*$/,
      /\n\*\*Status:\*\*[^\n]*(?:\n\*\*[^*]+:\*\*[^\n]*)*\s*$/,
      /\n##\s*Meta(?:dados?|data)?\s*\n[\s\S]*?\*\*Status:\*\*[\s\S]*?$/i
    ];
    let result = content;
    for (const pattern of footerPatterns) {
      result = result.replace(pattern, "");
    }
    return result.trimEnd() + "\n";
  }
  /**
   * Add frontmatter to content
   */
  addFrontmatter(content, frontmatter) {
    const yaml = this.frontmatterToYaml(frontmatter);
    return `---
${yaml}---

${content}`;
  }
  /**
   * Convert frontmatter object to YAML string
   */
  frontmatterToYaml(fm) {
    const lines = [];
    lines.push(`id: ${fm.id}`);
    lines.push(`type: ${fm.type}`);
    if (fm.modules.length > 0) {
      lines.push(`modules: [${fm.modules.join(", ")}]`);
    } else {
      lines.push(`modules: []`);
    }
    if (fm.epic) {
      lines.push(`epic: ${fm.epic}`);
    }
    lines.push(`status: ${fm.status}`);
    lines.push(`created: ${fm.created}`);
    lines.push(`updated: ${fm.updated}`);
    return lines.join("\n") + "\n";
  }
  /**
   * Get all CARF markdown files
   */
  getCARFFiles() {
    const files = [];
    const processFolder = (folder) => {
      for (const child of folder.children) {
        if (child instanceof import_obsidian6.TFile && child.extension === "md") {
          if (Document.isInCARFPath(child.path)) {
            files.push(child);
          }
        } else if (child instanceof import_obsidian6.TFolder) {
          processFolder(child);
        }
      }
    };
    const root = this.app.vault.getRoot();
    processFolder(root);
    return files;
  }
};

// src/views/DashboardView.ts
var import_obsidian7 = require("obsidian");
var DASHBOARD_VIEW_TYPE = "carf-dashboard";
var DashboardView = class extends import_obsidian7.ItemView {
  constructor(leaf, validationService, onStartReview) {
    super(leaf);
    this.validationService = validationService;
    this.onStartReview = onStartReview;
  }
  getViewType() {
    return DASHBOARD_VIEW_TYPE;
  }
  getDisplayText() {
    return "CARF";
  }
  getIcon() {
    return "file-check";
  }
  async onOpen() {
    this.containerEl.children[1].addClass("carf-dashboard");
    await this.render();
  }
  async render() {
    const el = this.containerEl.children[1];
    el.empty();
    const result = this.validationService.getLastResult();
    if (!result) {
      el.createSpan({ text: "carregando...", cls: "carf-loading" });
      await this.validationService.validateAll();
      await this.render();
      return;
    }
    const header = el.createDiv({ cls: "carf-header" });
    header.createEl("h2", { text: "CARF" });
    const refresh = header.createEl("a", { text: "atualizar" });
    refresh.onclick = async () => {
      await this.validationService.validateAll();
      await this.render();
    };
    const docs = result.documents.filter((d) => d.file.name !== "README.md");
    const byStatus = this.validationService.getDocumentsByStatus(docs);
    const stats = el.createDiv({ cls: "carf-stats" });
    this.inlineStat(stats, docs.length, "total");
    this.inlineStat(stats, byStatus.approved.length, "approved", "#4ade80");
    this.inlineStat(stats, byStatus.rejected.length, "rejected", "#f87171");
    this.inlineStat(stats, byStatus.review.length, "review");
    if (byStatus.review.length > 0) {
      const btn = el.createEl("button", {
        text: `revisar ${byStatus.review.length} \u2192`,
        cls: "carf-start-btn"
      });
      btn.onclick = () => this.onStartReview();
    }
    const docPaths = new Set(docs.map((d) => d.file.path));
    const issues = result.issues.filter((i) => docPaths.has(i.file.path));
    if (issues.length > 0) {
      el.createDiv({ text: `${issues.length} issues`, cls: "carf-issues-title" });
      const list = el.createDiv({ cls: "carf-issues-list" });
      for (const issue of issues.slice(0, 30)) {
        const row = list.createDiv({ cls: "carf-issue-row" });
        row.textContent = `${issue.icon} ${issue.file.basename}: ${issue.message}`;
        row.onclick = () => this.openIssue(issue);
      }
      if (issues.length > 30) {
        el.createDiv({ text: `+${issues.length - 30} mais`, cls: "carf-more" });
      }
    }
  }
  inlineStat(container, value, label, color) {
    const s = container.createSpan({ cls: "carf-stat" });
    const num = s.createSpan({ text: value.toString(), cls: "carf-stat-num" });
    if (color)
      num.style.color = color;
    s.createSpan({ text: label, cls: "carf-stat-label" });
  }
  async openIssue(issue) {
    var _a;
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(issue.file);
    if (issue.line) {
      const editor = (_a = leaf.view) == null ? void 0 : _a.editor;
      if (editor)
        editor.setCursor({ line: issue.line - 1, ch: 0 });
    }
  }
};

// src/views/ReviewView.ts
var import_obsidian8 = require("obsidian");
var REVIEW_VIEW_TYPE = "carf-review";
var ReviewView = class extends import_obsidian8.ItemView {
  constructor(leaf, metadataService, validationService) {
    super(leaf);
    this.queue = [];
    this.index = 0;
    this.doc = null;
    this.issues = [];
    this.metadataService = metadataService;
    this.validationService = validationService;
  }
  getViewType() {
    return REVIEW_VIEW_TYPE;
  }
  getDisplayText() {
    return "Review";
  }
  getIcon() {
    return "check-square";
  }
  async onOpen() {
    this.containerEl.children[1].addClass("carf-rv");
    await this.loadQueue();
    await this.render();
    this.registerDomEvent(document, "keydown", this.onKey.bind(this));
  }
  async loadQueue() {
    var _a;
    const result = this.validationService.getLastResult();
    if (!result)
      await this.validationService.validateAll();
    const docs = ((_a = this.validationService.getLastResult()) == null ? void 0 : _a.documents) || [];
    this.queue = docs.filter((d) => d.file.name !== "README.md" && d.status === "review" /* REVIEW */).map((d) => d.file);
    this.index = 0;
  }
  async render() {
    const el = this.containerEl.children[1];
    el.empty();
    if (this.queue.length === 0) {
      const empty = el.createDiv({ cls: "carf-rv-empty" });
      empty.createEl("div", { text: "\u2713", cls: "carf-rv-done-icon" });
      empty.createEl("div", { text: "Nenhum arquivo para revisar", cls: "carf-rv-done-text" });
      return;
    }
    const file = this.queue[this.index];
    this.doc = await this.metadataService.parseDocument(file);
    this.issues = await this.validationService.validateFile(file);
    const counter = el.createDiv({ cls: "carf-rv-counter" });
    counter.createSpan({ text: `${this.index + 1}`, cls: "carf-rv-current" });
    counter.createSpan({ text: ` / ${this.queue.length}` });
    el.createEl("h2", {
      text: this.doc.title || file.basename,
      cls: "carf-rv-title"
    });
    el.createDiv({ text: file.path, cls: "carf-rv-path" });
    if (!this.doc.frontmatter) {
      const initBtn = el.createEl("button", {
        text: "criar yaml",
        cls: "carf-rv-init"
      });
      initBtn.onclick = () => this.initYaml();
    }
    if (this.issues.length > 0) {
      const issuesEl = el.createDiv({ cls: "carf-rv-issues" });
      for (const issue of this.issues) {
        const row = issuesEl.createDiv({ cls: "carf-rv-issue" });
        row.createSpan({ text: issue.icon + " " + issue.message });
      }
    }
    const preview = el.createDiv({ cls: "carf-rv-preview" });
    const content = this.metadataService.getBodyContent(this.doc.content);
    await import_obsidian8.MarkdownRenderer.render(this.app, content, preview, file.path, this);
    const actions = el.createDiv({ cls: "carf-rv-actions" });
    const prevBtn = actions.createEl("button", { text: "\u2190", cls: "carf-rv-btn" });
    prevBtn.disabled = this.index === 0;
    prevBtn.onclick = () => this.prev();
    const rejectBtn = actions.createEl("button", { text: "\u2717 Rejeitar", cls: "carf-rv-btn carf-rv-reject" });
    rejectBtn.onclick = () => this.reject();
    const approveBtn = actions.createEl("button", { text: "\u2713 Aprovar", cls: "carf-rv-btn carf-rv-approve" });
    approveBtn.onclick = () => this.approve();
    const skipBtn = actions.createEl("button", { text: "\u2192", cls: "carf-rv-btn" });
    skipBtn.onclick = () => this.next();
    const openLink = el.createDiv({ cls: "carf-rv-open" });
    const link = openLink.createEl("a", { text: "abrir no editor" });
    link.onclick = () => this.openInEditor();
  }
  async approve() {
    if (!this.doc)
      return;
    await this.metadataService.setStatus(this.doc.file, "approved" /* APPROVED */);
    this.queue.splice(this.index, 1);
    if (this.index >= this.queue.length)
      this.index = Math.max(0, this.queue.length - 1);
    await this.render();
  }
  async reject() {
    if (!this.doc)
      return;
    await this.metadataService.setStatus(this.doc.file, "rejected" /* REJECTED */);
    this.queue.splice(this.index, 1);
    if (this.index >= this.queue.length)
      this.index = Math.max(0, this.queue.length - 1);
    await this.render();
  }
  async next() {
    if (this.index < this.queue.length - 1) {
      this.index++;
      await this.render();
    }
  }
  async prev() {
    if (this.index > 0) {
      this.index--;
      await this.render();
    }
  }
  async openInEditor() {
    if (!this.doc)
      return;
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(this.doc.file);
  }
  async initYaml() {
    if (!this.doc)
      return;
    await this.metadataService.initFrontmatter(this.doc.file);
    await this.render();
  }
  onKey(e) {
    if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement)
      return;
    if (e.key === "ArrowLeft")
      this.prev();
    else if (e.key === "ArrowRight")
      this.next();
    else if (e.key.toLowerCase() === "a" && !e.ctrlKey)
      this.approve();
    else if (e.key.toLowerCase() === "r" && !e.ctrlKey)
      this.reject();
  }
};

// src/commands/InitMetadataCommand.ts
var import_obsidian9 = require("obsidian");
var InitMetadataCommand = class {
  constructor(app, metadataService) {
    this.app = app;
    this.metadataService = metadataService;
  }
  /**
   * Execute the command
   */
  async execute() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian9.Notice("Nenhum arquivo aberto");
      return;
    }
    if (!activeFile.name.endsWith(".md")) {
      new import_obsidian9.Notice("Apenas arquivos Markdown suportados");
      return;
    }
    const hasFrontmatter = await this.metadataService.hasFrontmatter(activeFile);
    if (hasFrontmatter) {
      new import_obsidian9.Notice("Arquivo j\xE1 possui frontmatter");
      return;
    }
    if (!Document.isInCARFPath(activeFile.path)) {
      new import_obsidian9.Notice("Arquivo n\xE3o est\xE1 em um caminho CARF (CENTRAL/ ou PROJECTS/)");
      return;
    }
    const frontmatter = await this.metadataService.initFrontmatter(activeFile);
    new import_obsidian9.Notice(
      `Frontmatter criado:
ID: ${frontmatter.id}
Tipo: ${frontmatter.type}
Status: ${frontmatter.status}`
    );
  }
};

// src/commands/MigrateFooterCommand.ts
var import_obsidian10 = require("obsidian");
var MigrateFooterCommand = class {
  constructor(app, migrationService) {
    this.app = app;
    this.migrationService = migrationService;
  }
  /**
   * Execute the command for current file
   */
  async execute() {
    var _a, _b;
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian10.Notice("Nenhum arquivo aberto");
      return;
    }
    if (!activeFile.name.endsWith(".md")) {
      new import_obsidian10.Notice("Apenas arquivos Markdown suportados");
      return;
    }
    const result = await this.migrationService.migrateFile(activeFile);
    if (result.success) {
      new import_obsidian10.Notice(
        `Migra\xE7\xE3o conclu\xEDda!
ID: ${(_a = result.newFrontmatter) == null ? void 0 : _a.id}
Status: ${(_b = result.newFrontmatter) == null ? void 0 : _b.status}`
      );
    } else {
      new import_obsidian10.Notice(`Migra\xE7\xE3o falhou: ${result.message}`);
    }
  }
  /**
   * Execute the command for all files
   */
  async executeAll() {
    new import_obsidian10.Notice("Iniciando migra\xE7\xE3o de todos os arquivos...");
    await this.migrationService.migrateAll();
  }
};

// src/commands/ValidateCommand.ts
var import_obsidian11 = require("obsidian");
var ValidateCommand = class {
  constructor(app, validationService) {
    this.app = app;
    this.validationService = validationService;
  }
  /**
   * Validate the current file
   */
  async executeFile() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian11.Notice("Nenhum arquivo aberto");
      return;
    }
    if (!activeFile.name.endsWith(".md")) {
      new import_obsidian11.Notice("Apenas arquivos Markdown suportados");
      return;
    }
    const issues = await this.validationService.validateFile(activeFile);
    if (issues.length === 0) {
      new import_obsidian11.Notice("\u2713 Nenhum problema encontrado!");
      return;
    }
    const errors = issues.filter((i) => i.severity === "error" /* ERROR */).length;
    const warnings = issues.filter((i) => i.severity === "warning" /* WARNING */).length;
    const info = issues.filter((i) => i.severity === "info" /* INFO */).length;
    new import_obsidian11.Notice(
      `Problemas encontrados:
\u2717 ${errors} erros
\u26A0 ${warnings} avisos
\u2139 ${info} info

Abra o Dashboard para detalhes.`
    );
  }
  /**
   * Validate all files in the vault
   */
  async executeAll() {
    new import_obsidian11.Notice("Validando todos os arquivos...");
    const result = await this.validationService.validateAll();
    new import_obsidian11.Notice(
      `Valida\xE7\xE3o conclu\xEDda:
${result.documents.length} arquivos analisados
\u2717 ${result.summary.errors} erros
\u26A0 ${result.summary.warnings} avisos
\u2139 ${result.summary.info} info`
    );
  }
};

// src/commands/ApproveCommand.ts
var import_obsidian12 = require("obsidian");
var ApproveCommand = class {
  constructor(app, metadataService) {
    this.app = app;
    this.metadataService = metadataService;
  }
  /**
   * Execute the command
   */
  async execute() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian12.Notice("Nenhum arquivo aberto");
      return;
    }
    if (!activeFile.name.endsWith(".md")) {
      new import_obsidian12.Notice("Apenas arquivos Markdown suportados");
      return;
    }
    const hasFrontmatter = await this.metadataService.hasFrontmatter(activeFile);
    if (!hasFrontmatter) {
      new import_obsidian12.Notice("Arquivo n\xE3o possui frontmatter. Execute 'CARF: Init Metadata' primeiro.");
      return;
    }
    if (!Document.isInCARFPath(activeFile.path)) {
      new import_obsidian12.Notice("Arquivo n\xE3o est\xE1 em um caminho CARF");
      return;
    }
    await this.metadataService.setStatus(activeFile, "approved" /* APPROVED */);
    new import_obsidian12.Notice("\u2713 Documento aprovado!");
  }
};

// src/commands/RejectCommand.ts
var import_obsidian13 = require("obsidian");
var RejectCommand = class {
  constructor(app, metadataService) {
    this.app = app;
    this.metadataService = metadataService;
  }
  /**
   * Execute the command
   */
  async execute() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian13.Notice("Nenhum arquivo aberto");
      return;
    }
    if (!activeFile.name.endsWith(".md")) {
      new import_obsidian13.Notice("Apenas arquivos Markdown suportados");
      return;
    }
    const hasFrontmatter = await this.metadataService.hasFrontmatter(activeFile);
    if (!hasFrontmatter) {
      new import_obsidian13.Notice("Arquivo n\xE3o possui frontmatter. Execute 'CARF: Init Metadata' primeiro.");
      return;
    }
    if (!Document.isInCARFPath(activeFile.path)) {
      new import_obsidian13.Notice("Arquivo n\xE3o est\xE1 em um caminho CARF");
      return;
    }
    await this.metadataService.setStatus(activeFile, "rejected" /* REJECTED */);
    new import_obsidian13.Notice("\u2717 Documento rejeitado!");
  }
};

// src/commands/SyncIndexCommand.ts
var import_obsidian14 = require("obsidian");
var SyncIndexCommand = class {
  constructor(app, indexService) {
    this.app = app;
    this.indexService = indexService;
  }
  /**
   * Execute the command for current folder
   */
  async execute() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian14.Notice("Nenhum arquivo aberto");
      return;
    }
    const folder = activeFile.parent;
    if (!folder) {
      new import_obsidian14.Notice("N\xE3o foi poss\xEDvel determinar a pasta");
      return;
    }
    if (!Document.isInCARFPath(folder.path)) {
      new import_obsidian14.Notice("Pasta n\xE3o est\xE1 em um caminho CARF");
      return;
    }
    await this.indexService.syncFolderIndex(folder);
    new import_obsidian14.Notice("\u2713 \xCDndice do README atualizado!");
  }
  /**
   * Sync all README indexes in the vault
   */
  async executeAll() {
    new import_obsidian14.Notice("Atualizando todos os \xEDndices...");
    const folders = this.getAllCARFFolders();
    let updated = 0;
    for (const folder of folders) {
      const readmePath = `${folder.path}/README.md`;
      if (this.app.vault.getAbstractFileByPath(readmePath)) {
        await this.indexService.syncFolderIndex(folder);
        updated++;
      }
    }
    new import_obsidian14.Notice(`\u2713 ${updated} \xEDndices atualizados!`);
  }
  /**
   * Get all folders in CARF paths
   */
  getAllCARFFolders() {
    const folders = [];
    const processFolder = (folder) => {
      if (Document.isInCARFPath(folder.path)) {
        folders.push(folder);
      }
      for (const child of folder.children) {
        if (child instanceof import_obsidian14.TFolder) {
          processFolder(child);
        }
      }
    };
    const root = this.app.vault.getRoot();
    processFolder(root);
    return folders;
  }
};

// main.ts
var CARF_ICON = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><path d="M9 15l2 2 4-4"></path></svg>`;
var CARFPlugin = class extends import_obsidian15.Plugin {
  async onload() {
    console.log("Loading CARF Plugin");
    await this.loadSettings();
    (0, import_obsidian15.addIcon)("carf-icon", CARF_ICON);
    this.metadataService = new MetadataService(this.app);
    this.validationService = new ValidationService(this.app, this.metadataService);
    this.indexService = new IndexService(this.app, this.metadataService);
    this.migrationService = new MigrationService(this.app, this.metadataService);
    for (const validator of this.validationService.getValidators()) {
      const enabled = this.settings.enabledValidators.includes(validator.id);
      this.validationService.setValidatorEnabled(validator.id, enabled);
    }
    this.initMetadataCommand = new InitMetadataCommand(this.app, this.metadataService);
    this.migrateFooterCommand = new MigrateFooterCommand(this.app, this.migrationService);
    this.validateCommand = new ValidateCommand(this.app, this.validationService);
    this.approveCommand = new ApproveCommand(this.app, this.metadataService);
    this.rejectCommand = new RejectCommand(this.app, this.metadataService);
    this.syncIndexCommand = new SyncIndexCommand(this.app, this.indexService);
    this.registerView(
      DASHBOARD_VIEW_TYPE,
      (leaf) => new DashboardView(leaf, this.validationService, () => this.activateReview())
    );
    this.registerView(
      REVIEW_VIEW_TYPE,
      (leaf) => new ReviewView(leaf, this.metadataService, this.validationService)
    );
    this.registerCommands();
    this.registerEventHandlers();
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.setText("CARF: Loading...");
    this.statusBarItem.addClass("carf-status-bar");
    this.addSettingTab(new CARFSettingTab(this.app, this));
    this.addRibbonIcon("carf-icon", "Open CARF Dashboard", () => {
      this.activateDashboard();
    });
    this.app.workspace.onLayoutReady(() => {
      this.runInitialValidation();
    });
  }
  async onunload() {
    console.log("Unloading CARF Plugin");
  }
  /**
   * Register all plugin commands
   */
  registerCommands() {
    this.addCommand({
      id: "init-metadata",
      name: "Init Metadata",
      callback: () => this.initMetadataCommand.execute()
    });
    this.addCommand({
      id: "migrate-footer",
      name: "Migrate Footer",
      callback: () => this.migrateFooterCommand.execute()
    });
    this.addCommand({
      id: "migrate-all-footers",
      name: "Migrate All Footers",
      callback: () => this.migrateFooterCommand.executeAll()
    });
    this.addCommand({
      id: "validate-file",
      name: "Validate File",
      hotkeys: [{ modifiers: ["Ctrl", "Shift"], key: "v" }],
      callback: () => this.validateCommand.executeFile()
    });
    this.addCommand({
      id: "validate-all",
      name: "Validate All",
      callback: () => this.validateCommand.executeAll()
    });
    this.addCommand({
      id: "approve",
      name: "Approve",
      hotkeys: [{ modifiers: ["Ctrl", "Shift"], key: "a" }],
      callback: () => this.approveCommand.execute()
    });
    this.addCommand({
      id: "reject",
      name: "Reject",
      hotkeys: [{ modifiers: ["Ctrl", "Shift"], key: "r" }],
      callback: () => this.rejectCommand.execute()
    });
    this.addCommand({
      id: "sync-index",
      name: "Sync Index",
      callback: () => this.syncIndexCommand.execute()
    });
    this.addCommand({
      id: "sync-all-indexes",
      name: "Sync All Indexes",
      callback: () => this.syncIndexCommand.executeAll()
    });
    this.addCommand({
      id: "open-dashboard",
      name: "Open Dashboard",
      callback: () => this.activateDashboard()
    });
    this.addCommand({
      id: "open-review",
      name: "Open Review Mode",
      callback: () => this.activateReview()
    });
  }
  /**
   * Register event handlers for file changes
   */
  registerEventHandlers() {
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (!(file instanceof import_obsidian15.TFile))
          return;
        if (!file.name.endsWith(".md"))
          return;
        if (!Document.isInCARFPath(file.path))
          return;
        if (this.settings.autoUpdateTimestamp) {
          setTimeout(async () => {
            try {
              const hasFrontmatter = await this.metadataService.hasFrontmatter(file);
              if (hasFrontmatter) {
                await this.metadataService.updateTimestamp(file);
              }
            } catch (e) {
              console.error("Failed to update timestamp:", e);
            }
          }, 100);
        }
        if (this.settings.autoValidateOnSave) {
          const issues = await this.validationService.validateFile(file);
          this.updateStatusBar();
        }
        if (this.settings.autoSyncIndex && file.parent) {
          if (this.indexService.shouldSyncIndex(file)) {
            this.indexService.scheduleSync(file.parent);
          }
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("create", async (file) => {
        if (!(file instanceof import_obsidian15.TFile))
          return;
        if (!file.name.endsWith(".md"))
          return;
        if (!Document.isInCARFPath(file.path))
          return;
        const type = Document.inferTypeFromFilename(file.name);
        if (type !== "OTHER" && type !== "README") {
          console.log(`CARF: New ${type} file created: ${file.name}`);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", async (file, oldPath) => {
        if (!(file instanceof import_obsidian15.TFile))
          return;
        if (!file.name.endsWith(".md"))
          return;
        if (this.settings.autoSyncIndex) {
          const oldFolderPath = oldPath.substring(0, oldPath.lastIndexOf("/"));
          const oldFolder = this.app.vault.getAbstractFileByPath(oldFolderPath);
          if (oldFolder instanceof import_obsidian15.TFolder && Document.isInCARFPath(oldFolderPath)) {
            this.indexService.scheduleSync(oldFolder);
          }
          if (file.parent && Document.isInCARFPath(file.parent.path)) {
            this.indexService.scheduleSync(file.parent);
          }
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", async (file) => {
        if (!(file instanceof import_obsidian15.TFile))
          return;
        if (this.settings.autoSyncIndex) {
          const folderPath = file.path.substring(0, file.path.lastIndexOf("/"));
          const folder = this.app.vault.getAbstractFileByPath(folderPath);
          if (folder instanceof import_obsidian15.TFolder && Document.isInCARFPath(folderPath)) {
            this.indexService.scheduleSync(folder);
          }
        }
      })
    );
  }
  /**
   * Run initial validation when plugin loads
   */
  async runInitialValidation() {
    try {
      await this.validationService.validateAll();
      this.updateStatusBar();
    } catch (e) {
      console.error("Initial validation failed:", e);
      this.statusBarItem.setText("CARF: Error");
    }
  }
  /**
   * Update status bar with current stats
   */
  updateStatusBar() {
    const result = this.validationService.getLastResult();
    if (!result) {
      this.statusBarItem.setText("CARF: No data");
      return;
    }
    const byStatus = this.validationService.getDocumentsByStatus(result.documents);
    const errors = result.summary.errors;
    const warnings = result.summary.warnings;
    this.statusBarItem.setText(
      `CARF: \u2713 ${byStatus.approved.length} | \u2717 ${byStatus.rejected.length} | \u25CB ${byStatus.review.length} | ! ${errors + warnings} issues`
    );
    this.statusBarItem.onclick = () => this.activateDashboard();
  }
  /**
   * Activate the dashboard view
   */
  async activateDashboard() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(DASHBOARD_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: DASHBOARD_VIEW_TYPE,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  /**
   * Activate the review view
   */
  async activateReview() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(REVIEW_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getLeaf(true);
      if (leaf) {
        await leaf.setViewState({
          type: REVIEW_VIEW_TYPE,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  /**
   * Load plugin settings
   */
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  /**
   * Save plugin settings
   */
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
